global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apps/v1'
    static_configs:
      - targets: ['https://127.0.0.1:51379/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy']